name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex

    steps:
      - uses: actions/checkout@v3

      - name: creates output
        run: sh ./build.sh

      - name: Pushes to origin repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: "output"
          destination-github-username: sem201 #ë˜ëŠ” ì‚¬ìš©í•  ê¹ƒí—ˆë¸Œ ìœ ì €ì´ë¦„
          destination-repository-name: #[repo ì´ë¦„]
          user-email: ${{secrets.EMAIL}} # ê¹ƒí—ˆë¸Œ ì‹œí¬ë¦¿ì— EMAILê°’ìœ¼ë¡œ ë°›ê¸°
          commit-message: "ë°°í¬ ğŸ±â€ğŸ"

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
